"""
Meta-Learning Research Agent.

Runs weekly (Sunday 9 PM ET, after compaction). Does two things:
1. TRADE OUTCOME ANALYSIS: Correlates which categories/signals had the highest IC
   over the last 7 days of closed trades. Flags over/under-performing signals.
2. RESEARCH SCAN: Polls arXiv q-fin + SSRN RSS for new papers published this week.
   Ollama summarizes each. If relevant to our system, flags it.

Output: Writes a markdown proposal to docs/update_proposals/YYYY-MM-DD.md
        + sends Discord alert if high-priority finding.

All LLM work is done locally via Ollama (free). Claude is NOT called here.
"""

from __future__ import annotations

import asyncio
import os
from datetime import datetime, timedelta
from pathlib import Path

import feedparser
import httpx
from loguru import logger

from core.config import settings
from core.redis_client import cache_get, cache_set

# arXiv q-fin RSS feeds
ARXIV_FEEDS = [
    ("q-fin.TR", "http://export.arxiv.org/rss/q-fin.TR"),   # Trading + Market Microstructure
    ("q-fin.PM", "http://export.arxiv.org/rss/q-fin.PM"),   # Portfolio Management
    ("q-fin.ST", "http://export.arxiv.org/rss/q-fin.ST"),   # Statistical Finance
    ("q-fin.CP", "http://export.arxiv.org/rss/q-fin.CP"),   # Computational Finance
]

# SSRN derivatives / quant finance topic
SSRN_FEEDS = [
    ("ssrn_derivatives", "https://papers.ssrn.com/sol3/RSS.cfm?topic_id=1318"),
    ("ssrn_quant",       "https://papers.ssrn.com/sol3/RSS.cfm?topic_id=1360"),
]

# Keywords that make a paper relevant to our system
RELEVANCE_KEYWORDS = [
    "options", "implied volatility", "candlestick", "momentum", "earnings",
    "IV crush", "skew", "term structure", "PEAD", "earnings surprise",
    "factor", "information coefficient", "alpha", "backtest", "piotroski",
    "insider", "analyst revision", "sentiment", "GEX", "delta hedge",
    "machine learning", "XGBoost", "LightGBM", "neural network", "LSTM",
    "calendar spread", "iron condor", "VIX", "volatility risk premium",
]

PROPOSALS_DIR = Path(__file__).resolve().parents[2] / "docs" / "update_proposals"


async def run_meta_research() -> str:
    """
    Main entry point. Returns path to written proposal file.
    Called by the weekly scheduler in main.py.
    """
    PROPOSALS_DIR.mkdir(parents=True, exist_ok=True)

    today = datetime.utcnow().strftime("%Y-%m-%d")
    proposal_path = PROPOSALS_DIR / f"{today}.md"

    sections: list[str] = [
        f"# System Update Proposal — {today}",
        f"*Auto-generated by meta_researcher agent at {datetime.utcnow().strftime('%H:%M UTC')}*\n",
    ]

    # 1. Trade outcome analysis
    outcome_section = await _analyze_trade_outcomes()
    sections.append(outcome_section)

    # 2. Agent performance summary
    monitor_section = await _summarize_agent_performance()
    sections.append(monitor_section)

    # 3. Research paper scan
    papers_section = await _scan_research_papers()
    sections.append(papers_section)

    # 4. Write proposal
    proposal_text = "\n\n".join(sections)
    proposal_path.write_text(proposal_text, encoding="utf-8")
    logger.info(f"Meta-researcher: proposal written to {proposal_path}")

    # 5. Discord alert if high-priority findings
    if "🔴" in proposal_text or "HIGH PRIORITY" in proposal_text:
        await _discord_alert(f"⚠️ High-priority system update proposal generated: {today}. Check docs/update_proposals/{today}.md")

    return str(proposal_path)


async def _analyze_trade_outcomes() -> str:
    """
    Pull last 7 days of closed trades + their category scores.
    Compute which categories most correlated with wins vs losses.
    """
    lines = ["## 1. Trade Outcome Analysis (Last 7 Days)"]

    try:
        from core.database import AsyncSessionLocal
        from sqlalchemy import text

        async with AsyncSessionLocal() as session:
            # Get closed trades from last 7 days
            result = await session.execute(text("""
                SELECT t.id, t.symbol, t.direction, t.realized_pnl, t.strategy,
                       t.entry_price, t.exit_price, t.opened_at, t.closed_at,
                       ar.total_score, ar.category_scores
                FROM trades t
                LEFT JOIN analysis_results ar ON ar.symbol = t.symbol
                    AND ar.analyzed_at BETWEEN t.opened_at - interval '1 hour'
                                           AND t.opened_at + interval '1 hour'
                WHERE t.closed_at > NOW() - interval '7 days'
                  AND t.realized_pnl IS NOT NULL
                ORDER BY t.closed_at DESC
                LIMIT 50
            """))
            trades = [dict(r) for r in result.mappings()]

        if not trades:
            return "## 1. Trade Outcome Analysis\n\nNo closed trades in last 7 days."

        wins   = [t for t in trades if (t.get("realized_pnl") or 0) > 0]
        losses = [t for t in trades if (t.get("realized_pnl") or 0) <= 0]
        win_rate = len(wins) / len(trades) * 100

        lines.append(f"**{len(trades)} trades closed** | Win rate: {win_rate:.0f}% ({len(wins)}W / {len(losses)}L)\n")

        # Category IC: for each trade, look at which categories scored high/low
        # and whether the trade won or lost
        category_ic: dict[str, list[float]] = {}
        for t in trades:
            cat_scores = t.get("category_scores") or {}
            outcome = 1.0 if (t.get("realized_pnl") or 0) > 0 else 0.0
            for cat, score_data in cat_scores.items():
                if isinstance(score_data, dict):
                    raw = score_data.get("raw_score", 5)
                    normalized = (raw - 5) / 5  # -1 to +1
                    if cat not in category_ic:
                        category_ic[cat] = []
                    category_ic[cat].append(normalized * (2 * outcome - 1))

        if category_ic:
            lines.append("**Category IC (positive = correlated with wins):**\n")
            ic_sorted = sorted(
                [(cat, sum(v) / len(v)) for cat, v in category_ic.items() if len(v) >= 3],
                key=lambda x: abs(x[1]), reverse=True
            )
            for cat, ic in ic_sorted[:8]:
                bar = "↑" if ic > 0.05 else "↓" if ic < -0.05 else "→"
                flag = " 🔴 UNDERPERFORMING" if ic < -0.10 else " 🟢 TOP SIGNAL" if ic > 0.15 else ""
                lines.append(f"- `{cat}`: IC={ic:+.3f} {bar}{flag}")

        # Worst losses detail
        if losses:
            worst = sorted(losses, key=lambda t: t.get("realized_pnl") or 0)[:3]
            lines.append("\n**Worst losses (learn from these):**")
            for t in worst:
                pnl = t.get("realized_pnl", 0)
                lines.append(f"- {t['symbol']} {t.get('strategy','?')} → ${pnl:.0f} | score was {t.get('total_score','?')}")

    except Exception as e:
        lines.append(f"*Trade analysis unavailable: {e}*")

    return "\n".join(lines)


async def _summarize_agent_performance() -> str:
    """Pull agent monitor stats and flag issues."""
    lines = ["## 2. Agent Performance This Week"]
    try:
        from agents.agent_monitor import get_agent_stats, get_recommendations
        stats = await get_agent_stats()
        recs  = await get_recommendations()

        if not stats:
            return "## 2. Agent Performance\n\n*No data collected yet.*"

        lines.append("| Agent | Calls | Avg ms | Fallback% | Model |")
        lines.append("|-------|-------|--------|-----------|-------|")
        for agent, s in sorted(stats.items()):
            model = ", ".join(s.get("models_used", {}).keys())
            fallback = s.get("fallback_rate_pct", 0)
            flag = " 🔴" if fallback > 20 else ""
            lines.append(
                f"| {agent} | {s['total_calls']} | {s.get('avg_response_ms','?')}ms "
                f"| {fallback}%{flag} | {model} |"
            )

        lines.append("\n**Recommendations:**")
        for r in recs:
            sev = "🔴 HIGH" if r["severity"] == "high" else "🟡" if r["severity"] == "medium" else "✅"
            lines.append(f"- {sev} `{r['agent']}`: {r['issue']} → {r['recommendation']}")

    except Exception as e:
        lines.append(f"*Agent monitor unavailable: {e}*")

    return "\n".join(lines)


async def _scan_research_papers() -> str:
    """
    Scan arXiv + SSRN RSS for new papers this week.
    Use Ollama to summarize each relevant paper (title + abstract).
    """
    lines = ["## 3. New Research Papers This Week"]

    cutoff = datetime.utcnow() - timedelta(days=7)
    relevant_papers: list[dict] = []

    all_feeds = ARXIV_FEEDS + SSRN_FEEDS
    for source, url in all_feeds:
        try:
            cache_key = f"meta_rss:{source}"
            cached = await cache_get(cache_key)
            if cached:
                import orjson
                entries = orjson.loads(cached)
            else:
                async with httpx.AsyncClient(timeout=10.0) as client:
                    resp = await client.get(url, headers={"User-Agent": "OptionsBot/1.0"}, follow_redirects=True)
                    feed = feedparser.parse(resp.text)
                entries = []
                for e in feed.entries[:20]:
                    title = e.get("title", "")
                    summary = e.get("summary", e.get("description", ""))[:500]
                    entries.append({"title": title, "summary": summary, "source": source, "url": e.get("link", "")})
                import orjson
                await cache_set(cache_key, orjson.dumps(entries).decode(), ttl=86400 * 7)

            for entry in entries:
                combined = (entry["title"] + " " + entry["summary"]).lower()
                if any(kw.lower() in combined for kw in RELEVANCE_KEYWORDS):
                    relevant_papers.append(entry)

        except Exception as e:
            logger.debug(f"Meta-researcher feed {source} failed: {e}")

    if not relevant_papers:
        lines.append("*No highly relevant papers found this week.*")
        return "\n".join(lines)

    lines.append(f"Found **{len(relevant_papers)} relevant papers**. Ollama summaries:\n")

    # Summarize top 5 with Ollama
    for paper in relevant_papers[:5]:
        summary = await _ollama_summarize(paper["title"], paper["summary"])
        priority = "HIGH PRIORITY" if any(
            kw in paper["title"].lower() for kw in ["options", "iv crush", "earnings", "volatility risk premium"]
        ) else "REVIEW"
        lines.append(f"### [{priority}] {paper['title']}")
        lines.append(f"*Source: {paper['source']}* | {paper['url']}")
        lines.append(f"\n{summary}\n")

    return "\n".join(lines)


async def _ollama_summarize(title: str, abstract: str) -> str:
    prompt = f"""Paper: {title}

Abstract: {abstract[:600]}

In 2-3 sentences: What is the key finding? Is it relevant to an options trading system
that uses IV analysis, candlestick patterns, earnings behavior, momentum, and fundamental
scoring? If yes, what specifically could be adopted?"""

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={"model": settings.OLLAMA_CHAT_MODEL, "prompt": prompt, "stream": False},
            )
            return resp.json().get("response", "Summary unavailable")
    except Exception:
        return "Summary unavailable (Ollama offline)"


async def _discord_alert(message: str) -> None:
    if not settings.DISCORD_WEBHOOK_URL:
        return
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            await client.post(settings.DISCORD_WEBHOOK_URL, json={"content": message})
    except Exception as e:
        logger.debug(f"Discord alert failed: {e}")
